# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- oraclejdk11
- openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

dist: trusty

# Отправлять уведомление на почту MorozovRoman.88@mail.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - MorozovRoman.88@mail.ru
    on_success: never # default: change
    on_failure: always # default: always